version: '2.1'
services:
    jupyter:
        build:
          context: .
          dockerfile: Dockerfile-headless
        image: docker.io/library/judgeresearch-featurefeeder-headless-dev
        restart: 'no'
        volumes:
            - ./JudgeResearchNotebooks:/home/jovyan/JudgeResearchEditable
        ports:
            - "8888:8888"
        environment:
            NB_UID: ${UID}
            NB_GID: ${GID}
            JUPYTER_TOKEN: JR
